spring:
  application:
    name: demo
  freemarker:
    cache: false
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/demo"
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
    open-in-view: false
    show-sql: true
  thymeleaf:
    cache: false